---
- name: Deploy environment locally
  hosts: localhost

  tasks:
  - name: install packages
    become: true
    package:
      name:
        - bash
        - git
        - neofetch
        - vim
      state: present

  - name: copy dotfiles
    copy: src=config_files/{{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'bashrc', dest: '~/.bashrc' }
      - { src: 'vimrc', dest: '~/.vimrc' }
      - { src: 'gitconfig', dest: '~/.gitconfig' }
      - { src: 'neofetch.conf', dest: '~/.config/neofetch/config.conf' }
